name: 🛠 Checkstyle Validation

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Run Checkstyle Validation
        run: ./gradlew checkstyleMain checkstyleTest --console=verbose

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: |
            **/build/reports/checkstyle/
